//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientePrac2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/ode/processes/CompraProcess")]
        public string ClientePrac2_localhost_CompraProcessService {
            get {
                return ((string)(this["ClientePrac2_localhost_CompraProcessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/ServiciosPracticaNueva/services/GestionAlmacen")]
        public string ClientePrac2_localhost_GestionAlmacen {
            get {
                return ((string)(this["ClientePrac2_localhost_GestionAlmacen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/ServiciosPracticaNueva/services/GestionProveedor2")]
        public string ClientePrac2_localhost_GestionProveedor2 {
            get {
                return ((string)(this["ClientePrac2_localhost_GestionProveedor2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/ServiciosPracticaNueva/services/GestionProveedor3")]
        public string ClientePrac2_localhost_GestionProveedor3 {
            get {
                return ((string)(this["ClientePrac2_localhost_GestionProveedor3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/ServiciosPracticaNueva/services/GestionProveedor1")]
        public string ClientePrac2_localhost_GestionProveedor1 {
            get {
                return ((string)(this["ClientePrac2_localhost_GestionProveedor1"]));
            }
        }
    }
}
