//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClientePrac2.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GestionProveedor1SOAP", Namespace="http://www.example.org/GestionProveedor1/")]
    public partial class GestionProveedor1SOAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SolicitarPresupuestoOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrdenarCompraOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GestionProveedor1SOAP() {
            this.Url = global::ClientePrac2.Properties.Settings.Default.ClientePrac2_localhost_GestionProveedor1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SolicitarPresupuestoCompletedEventHandler SolicitarPresupuestoCompleted;
        
        /// <remarks/>
        public event OrdenarCompraCompletedEventHandler OrdenarCompraCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionProveedor1/SolicitarPresupuesto", RequestNamespace="http://www.example.org/GestionProveedor1/", ResponseNamespace="http://www.example.org/GestionProveedor1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float SolicitarPresupuesto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int numeroUnidades, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenciaProducto) {
            object[] results = this.Invoke("SolicitarPresupuesto", new object[] {
                        numeroUnidades,
                        referenciaProducto});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitarPresupuestoAsync(int numeroUnidades, string referenciaProducto) {
            this.SolicitarPresupuestoAsync(numeroUnidades, referenciaProducto, null);
        }
        
        /// <remarks/>
        public void SolicitarPresupuestoAsync(int numeroUnidades, string referenciaProducto, object userState) {
            if ((this.SolicitarPresupuestoOperationCompleted == null)) {
                this.SolicitarPresupuestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitarPresupuestoOperationCompleted);
            }
            this.InvokeAsync("SolicitarPresupuesto", new object[] {
                        numeroUnidades,
                        referenciaProducto}, this.SolicitarPresupuestoOperationCompleted, userState);
        }
        
        private void OnSolicitarPresupuestoOperationCompleted(object arg) {
            if ((this.SolicitarPresupuestoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitarPresupuestoCompleted(this, new SolicitarPresupuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionProveedor1/OrdenarCompra", RequestNamespace="http://www.example.org/GestionProveedor1/", ResponseNamespace="http://www.example.org/GestionProveedor1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool OrdenarCompra([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int numeroUnidades, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenciaProducto) {
            object[] results = this.Invoke("OrdenarCompra", new object[] {
                        numeroUnidades,
                        referenciaProducto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OrdenarCompraAsync(int numeroUnidades, string referenciaProducto) {
            this.OrdenarCompraAsync(numeroUnidades, referenciaProducto, null);
        }
        
        /// <remarks/>
        public void OrdenarCompraAsync(int numeroUnidades, string referenciaProducto, object userState) {
            if ((this.OrdenarCompraOperationCompleted == null)) {
                this.OrdenarCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrdenarCompraOperationCompleted);
            }
            this.InvokeAsync("OrdenarCompra", new object[] {
                        numeroUnidades,
                        referenciaProducto}, this.OrdenarCompraOperationCompleted, userState);
        }
        
        private void OnOrdenarCompraOperationCompleted(object arg) {
            if ((this.OrdenarCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrdenarCompraCompleted(this, new OrdenarCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CompraProcessBinding", Namespace="http://invoke.bpel.mtis/")]
    public partial class CompraProcessBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CompraProcessBinding() {
            this.Url = global::ClientePrac2.Properties.Settings.Default.ClientePrac2_localhost_CompraProcessService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event processCompletedEventHandler processCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://invoke.bpel.mtis/process", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CompraProcessResponse", Namespace="http://invoke.bpel.mtis/")]
        public CompraProcessResponse process([System.Xml.Serialization.XmlElementAttribute(Namespace="http://invoke.bpel.mtis/")] CompraProcessRequest CompraProcessRequest) {
            object[] results = this.Invoke("process", new object[] {
                        CompraProcessRequest});
            return ((CompraProcessResponse)(results[0]));
        }
        
        /// <remarks/>
        public void processAsync(CompraProcessRequest CompraProcessRequest) {
            this.processAsync(CompraProcessRequest, null);
        }
        
        /// <remarks/>
        public void processAsync(CompraProcessRequest CompraProcessRequest, object userState) {
            if ((this.processOperationCompleted == null)) {
                this.processOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessOperationCompleted);
            }
            this.InvokeAsync("process", new object[] {
                        CompraProcessRequest}, this.processOperationCompleted, userState);
        }
        
        private void OnprocessOperationCompleted(object arg) {
            if ((this.processCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processCompleted(this, new processCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GestionAlmacenSOAP", Namespace="http://www.example.org/GestionAlmacen/")]
    public partial class GestionAlmacenSOAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ComprobarStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarStockOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GestionAlmacenSOAP() {
            this.Url = global::ClientePrac2.Properties.Settings.Default.ClientePrac2_localhost_GestionAlmacen;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ComprobarStockCompletedEventHandler ComprobarStockCompleted;
        
        /// <remarks/>
        public event ActualizarStockCompletedEventHandler ActualizarStockCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionAlmacen/ComprobarStock", RequestNamespace="http://www.example.org/GestionAlmacen/", ResponseNamespace="http://www.example.org/GestionAlmacen/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("resultado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ComprobarStock([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int numeroUnidades, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenciaProducto) {
            object[] results = this.Invoke("ComprobarStock", new object[] {
                        numeroUnidades,
                        referenciaProducto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ComprobarStockAsync(int numeroUnidades, string referenciaProducto) {
            this.ComprobarStockAsync(numeroUnidades, referenciaProducto, null);
        }
        
        /// <remarks/>
        public void ComprobarStockAsync(int numeroUnidades, string referenciaProducto, object userState) {
            if ((this.ComprobarStockOperationCompleted == null)) {
                this.ComprobarStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnComprobarStockOperationCompleted);
            }
            this.InvokeAsync("ComprobarStock", new object[] {
                        numeroUnidades,
                        referenciaProducto}, this.ComprobarStockOperationCompleted, userState);
        }
        
        private void OnComprobarStockOperationCompleted(object arg) {
            if ((this.ComprobarStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ComprobarStockCompleted(this, new ComprobarStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionAlmacen/ActualizarStock", RequestNamespace="http://www.example.org/GestionAlmacen/", ResponseNamespace="http://www.example.org/GestionAlmacen/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("resultado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ActualizarStock([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int numeroUnidades, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenciaProducto) {
            object[] results = this.Invoke("ActualizarStock", new object[] {
                        numeroUnidades,
                        referenciaProducto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarStockAsync(int numeroUnidades, string referenciaProducto) {
            this.ActualizarStockAsync(numeroUnidades, referenciaProducto, null);
        }
        
        /// <remarks/>
        public void ActualizarStockAsync(int numeroUnidades, string referenciaProducto, object userState) {
            if ((this.ActualizarStockOperationCompleted == null)) {
                this.ActualizarStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarStockOperationCompleted);
            }
            this.InvokeAsync("ActualizarStock", new object[] {
                        numeroUnidades,
                        referenciaProducto}, this.ActualizarStockOperationCompleted, userState);
        }
        
        private void OnActualizarStockOperationCompleted(object arg) {
            if ((this.ActualizarStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarStockCompleted(this, new ActualizarStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GestionProveedor2SOAP", Namespace="http://www.example.org/GestionProveedor2/")]
    public partial class GestionProveedor2SOAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SolicitarPresupuestoOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrdenarCompraOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GestionProveedor2SOAP() {
            this.Url = global::ClientePrac2.Properties.Settings.Default.ClientePrac2_localhost_GestionProveedor2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SolicitarPresupuestoCompletedEventHandler SolicitarPresupuestoCompleted;
        
        /// <remarks/>
        public event OrdenarCompraCompletedEventHandler OrdenarCompraCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionProveedor2/SolicitarPresupuesto", RequestNamespace="http://www.example.org/GestionProveedor2/", ResponseNamespace="http://www.example.org/GestionProveedor2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float SolicitarPresupuesto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int numeroUnidades, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenciaProducto) {
            object[] results = this.Invoke("SolicitarPresupuesto", new object[] {
                        numeroUnidades,
                        referenciaProducto});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitarPresupuestoAsync(int numeroUnidades, string referenciaProducto) {
            this.SolicitarPresupuestoAsync(numeroUnidades, referenciaProducto, null);
        }
        
        /// <remarks/>
        public void SolicitarPresupuestoAsync(int numeroUnidades, string referenciaProducto, object userState) {
            if ((this.SolicitarPresupuestoOperationCompleted == null)) {
                this.SolicitarPresupuestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitarPresupuestoOperationCompleted);
            }
            this.InvokeAsync("SolicitarPresupuesto", new object[] {
                        numeroUnidades,
                        referenciaProducto}, this.SolicitarPresupuestoOperationCompleted, userState);
        }
        
        private void OnSolicitarPresupuestoOperationCompleted(object arg) {
            if ((this.SolicitarPresupuestoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitarPresupuestoCompleted(this, new SolicitarPresupuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionProveedor2/OrdenarCompra", RequestNamespace="http://www.example.org/GestionProveedor2/", ResponseNamespace="http://www.example.org/GestionProveedor2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool OrdenarCompra([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int numeroUnidades, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenciaProducto) {
            object[] results = this.Invoke("OrdenarCompra", new object[] {
                        numeroUnidades,
                        referenciaProducto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OrdenarCompraAsync(int numeroUnidades, string referenciaProducto) {
            this.OrdenarCompraAsync(numeroUnidades, referenciaProducto, null);
        }
        
        /// <remarks/>
        public void OrdenarCompraAsync(int numeroUnidades, string referenciaProducto, object userState) {
            if ((this.OrdenarCompraOperationCompleted == null)) {
                this.OrdenarCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrdenarCompraOperationCompleted);
            }
            this.InvokeAsync("OrdenarCompra", new object[] {
                        numeroUnidades,
                        referenciaProducto}, this.OrdenarCompraOperationCompleted, userState);
        }
        
        private void OnOrdenarCompraOperationCompleted(object arg) {
            if ((this.OrdenarCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrdenarCompraCompleted(this, new OrdenarCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GestionProveedor3SOAP", Namespace="http://www.example.org/GestionProveedor3/")]
    public partial class GestionProveedor3SOAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SolicitarPresupuestoOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrdenarCompraOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GestionProveedor3SOAP() {
            this.Url = global::ClientePrac2.Properties.Settings.Default.ClientePrac2_localhost_GestionProveedor3;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SolicitarPresupuestoCompletedEventHandler SolicitarPresupuestoCompleted;
        
        /// <remarks/>
        public event OrdenarCompraCompletedEventHandler OrdenarCompraCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionProveedor3/SolicitarPresupuesto", RequestNamespace="http://www.example.org/GestionProveedor3/", ResponseNamespace="http://www.example.org/GestionProveedor3/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float SolicitarPresupuesto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int numeroUnidades, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenciaProducto) {
            object[] results = this.Invoke("SolicitarPresupuesto", new object[] {
                        numeroUnidades,
                        referenciaProducto});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitarPresupuestoAsync(int numeroUnidades, string referenciaProducto) {
            this.SolicitarPresupuestoAsync(numeroUnidades, referenciaProducto, null);
        }
        
        /// <remarks/>
        public void SolicitarPresupuestoAsync(int numeroUnidades, string referenciaProducto, object userState) {
            if ((this.SolicitarPresupuestoOperationCompleted == null)) {
                this.SolicitarPresupuestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitarPresupuestoOperationCompleted);
            }
            this.InvokeAsync("SolicitarPresupuesto", new object[] {
                        numeroUnidades,
                        referenciaProducto}, this.SolicitarPresupuestoOperationCompleted, userState);
        }
        
        private void OnSolicitarPresupuestoOperationCompleted(object arg) {
            if ((this.SolicitarPresupuestoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitarPresupuestoCompleted(this, new SolicitarPresupuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/GestionProveedor3/OrdenarCompra", RequestNamespace="http://www.example.org/GestionProveedor3/", ResponseNamespace="http://www.example.org/GestionProveedor3/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool OrdenarCompra([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int numeroUnidades, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenciaProducto) {
            object[] results = this.Invoke("OrdenarCompra", new object[] {
                        numeroUnidades,
                        referenciaProducto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OrdenarCompraAsync(int numeroUnidades, string referenciaProducto) {
            this.OrdenarCompraAsync(numeroUnidades, referenciaProducto, null);
        }
        
        /// <remarks/>
        public void OrdenarCompraAsync(int numeroUnidades, string referenciaProducto, object userState) {
            if ((this.OrdenarCompraOperationCompleted == null)) {
                this.OrdenarCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrdenarCompraOperationCompleted);
            }
            this.InvokeAsync("OrdenarCompra", new object[] {
                        numeroUnidades,
                        referenciaProducto}, this.OrdenarCompraOperationCompleted, userState);
        }
        
        private void OnOrdenarCompraOperationCompleted(object arg) {
            if ((this.OrdenarCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrdenarCompraCompleted(this, new OrdenarCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://invoke.bpel.mtis/")]
    public partial class CompraProcessRequest {
        
        private int unidadesField;
        
        private string referenciaField;
        
        /// <comentarios/>
        public int unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
            }
        }
        
        /// <comentarios/>
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://invoke.bpel.mtis/")]
    public partial class CompraProcessResponse {
        
        private bool resultField;
        
        /// <comentarios/>
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SolicitarPresupuestoCompletedEventHandler(object sender, SolicitarPresupuestoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitarPresupuestoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitarPresupuestoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void OrdenarCompraCompletedEventHandler(object sender, OrdenarCompraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrdenarCompraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrdenarCompraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void processCompletedEventHandler(object sender, processCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompraProcessResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompraProcessResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ComprobarStockCompletedEventHandler(object sender, ComprobarStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComprobarStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ComprobarStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ActualizarStockCompletedEventHandler(object sender, ActualizarStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591